apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: frontend
build:
  tagPolicy:
    dateTime:
      format: 01/02_15:04:05
  artifacts:
  - image: frontend
    context: ../frontend
    docker:
      dockerfile: Dockerfile.dev
  #     requires:
  #     - image: image2
  #       alias: IMAGE2
  # - image: image2
  # 이런식으로 여러개 이미지와 이미지의 빌드 순서 지정가능
  local:        
    concurrency: 4
manifests:
  rawYaml:
    - deployment.yaml